version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/application/pi-sensor-v2
hooks:
  ApplicationStop:
    - location: scripts/deployment_scripts/stop_app.sh
      timeout: 300

  BeforeInstall:
    - location: scripts/deployment_scripts/install_dependencies.sh

  AfterInstall:
    - location: scripts/deployment_scripts/start_app.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/deployment_scripts/start_app.sh

  ValidateService:
    - location: scripts/deployment_scripts/validate_service.sh
      timeout: 300