version: 0.0
os: linux
files:
  - source: nginx/application.service
    destination: /etc/systemd/system/
  - source: nginx/application.conf
    destination: /etc/nginx/sites-available/
  - source: /
    destinaton: /var/www/application/pi-sensor-v2/
hooks:
  ApplicationStop:
    - location: scripts/deployment_scripts/stop_app.sh
      timeout: 300

  BeforeInstall:
    - location: scripts/deployment_scripts/install_dependencies.sh

  AfterInstall:
    - location: scripts/deployment_scripts/start_app.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/deployment_scripts/start_app.sh

  ValidateService:
    - location: scripts/deployment_scripts/validate_service.sh
      timeout: 300